replicaCount: 1

image:
  repository: ayushmaan7/mini-airbnb
  tag: "19"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

ingress:
  enabled: false

istio:
  enabled: true
  namespace: default

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  secretName: mini-airbnb-secrets

